FROM node:8-alpine

RUN apk add --update-cache --no-cache \
    curl make gcc g++ git python libc6-compat bash

# use changes to package.json to force Docker not to use the cache
# when we change our application's nodejs dependencies:
COPY package.json /tmp/package.json
COPY package-lock.json /tmp/package-lock.json
RUN cd /tmp && npm install
RUN mkdir -p /usr/src/app && cp -a /tmp/node_modules /usr/src/app/

WORKDIR /usr/src/app
COPY . /usr/src/app

ENTRYPOINT ["/usr/src/app/scripts/build.sh"]
